---
name: Docker
"on":
  # required by gomod-go-version-updater to trigger this action once pr has
  # been reviewed
  pull_request_review:
    types: [submitted]
  push:
permissions:
  contents: read
  packages: write
jobs:
  mcvs-docker-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: schubergphilis/mcvs-docker-action@v0.5.6
        with:
          dockle-accept-key: curl,HOME,libcrypto3,libssl3,PATH
          token: ${{ secrets.GITHUB_TOKEN }}
